#ifndef JOYSTICK_H
#define JOYSTICK_H


#ifdef PSP
#define PSP_BUTTON_TRIANGLE 0
#define PSP_BUTTON_CIRCLE 1
#define PSP_BUTTON_CROSS 2
#define PSP_BUTTON_SQUARE 3
#define PSP_BUTTON_LTRIGGER 4
#define PSP_BUTTON_RTRIGGER 5
#define PSP_BUTTON_DOWN 6
#define PSP_BUTTON_LEFT 7
#define PSP_BUTTON_UP 8
#define PSP_BUTTON_RIGHT 9
#define PSP_BUTTON_SELECT 10
#define PSP_BUTTON_START 11
#define PSP_BUTTON_HOME 12
#define PSP_BUTTON_HOLD 13
#endif

#endif // JOYSTICK_H

